package com.example.utils

object Localization {
    private val translations = mapOf(
        "ar" to mapOf(
            // App main
            "app_name" to "صيانة برو",
            "premium_version" to "النسخة الاحترافية",
            "nav_metrics" to "المؤشرات",
            "nav_tickets" to "التذاكر",
            "nav_settings" to "الإعدادات",
            "nav_notifications" to "الإشعارات",
            "user_profile" to "الملف الشخصي",

            // Activation
            "activation_title" to "تنشيط التطبيق",
            "activation_welcome" to "مرحباً بك في تطبيق صيانة الهواتف",
            "activation_desc" to "هذا التطبيق مرخص ويطلب إدخال مفتاح التفعيل عند الفتح لأول مرة.",
            "device_id_label" to "معرف الجهاز الخاص بك (DeviceID):",
            "device_id_copied" to "تم نسخ معرف الجهاز!",
            "activation_key_label" to "أدخل رمز التفعيل",
            "activation_key_placeholder" to "رمز التفعيل",
            "activation_key_required" to "الرجاء إدخال رمز التفعيل أولاً.",
            "activation_key_invalid" to "مفتاح تفعيل غير صالح أو غير مخصص لهذا الجهاز/السنة.",
            "activation_success" to "تم تنشيط التطبيق بنجاح!",
            "activate_now" to "تنشيط الآن",

            // Dashboard
            "dashboard_title" to "لوحة التحكم والإحصائيات",
            "total_tickets" to "إجمالي التذاكر المسجلة",
            "pending_tickets" to "تذاكر في انتظار الصيانة",
            "inprogress_tickets" to "تذاكر قيد العمل والإصلاح",
            "parts_needed_tickets" to "تذاكر معلقة لطلب قطع غيار",
            "completed_tickets" to "أجهزة جاهزة بانتظار العميل",
            "delivered_tickets" to "أجهزة تم تسليمها وتصفية الحساب",
            "financial_analysis" to "إحصائيات الأرباح",
            "expected_revenue" to "إجمالي الإيرادات المتوقعة",
            "collected_revenue" to "إجمالي المبالغ المحصلة (العربون)",
            "remaining_revenue" to "إجمالي المبالغ المتبقية في ذمة العملاء",
            "parts_needed_report" to "تقرير حالة قطع الغيار المستنفدة",
            "status_statistics" to "إحصائيات حالات الأجهزة",
            "percentage" to "النسبة المئوية",
            "ticket" to "تذكرة",
            "next_ticket_queue" to "التذكرة التالية في قائمة الانتظار",
            "start_maintenance" to "بدء الصيانة فورياً",
            "skip_next" to "تخطي للبطاقة التالية",
            "go_to_first" to "العودة للتذكرة الأولى",
            "phone_label" to "الهاتف:",
            "device_label" to "الجهاز:",
            "no_pending_queue" to "لا توجد تذاكر معلقة في قائمة الانتظار حالياً 👍",
            "current_maintenance_device" to "الجهاز الذي قيد الصيانة حالياً",
            "ready_delivery" to "جاهز للتسليم",
            "no_active_repairs" to "لا توجد أجهزة قيد الصيانة النشطة حالياً 👍",
            "forgotten_devices" to "أجهزة منسية طال انتظارها (جاهزة ولم تُستلم)",
            "today" to "اليوم",
            "since_1_day" to "منذ يوم واحد",
            "since_2_days" to "منذ يومين",
            "since_x_days" to "منذ %d أيام",
            "since_many_days" to "منذ %d يوماً",
            "no_forgotten_devices" to "لا توجد أجهزة منسية جاهزة للاستلام حالياً 👍",
            "call_client" to "اتصال بالعميل",
            "device_type_phone" to "نوع وهاتف الجهاز:",
            "device_fault" to "عطل الجهاز:",
            "entry_date" to "تاريخ الدخول:",
            "total_service_price" to "السعر الإجمالي للخدمة:",
            "advance_payment_label" to "المبلغ المدفوع (مقدماً):",
            "remaining_payment_label" to "المبلغ المتبقي:",
            "additional_notes_comments" to "ملاحظات وشروط إضافية:",
            "device_photos_title" to "الصور الموثقة للجهاز (انقر لعرضها بالكامل):",
            "change_maintenance_status" to "تغيير حالة الصيانة للتذكرة:",
            "share_pdf" to "مشاركة PDF",
            "share_text" to "واتساب / نص",
            "delete_selected_permanently" to "حذف التذكرة المحددة بصفة نهائية",
            "edit_ticket_dialog_title" to "تعديل بيانات التذكرة #",
            "save_edits" to "حفظ التعديلات",
            "cancel_btn" to "إلغاء",
            "confirm_delete_title" to "تأكيد الحذف الآمن",
            "confirm_delete_msg" to "هل أنت متأكد تماماً من رغبتك في حذف تذكرة صيانة العميل/الزبون (%s) نهائياً من النظام؟ لا يمكن الرجوع عن هذا الخيار بعد تأكيده.",
            "yes_confirm_delete" to "نعم، تأكيد الحذف",
            "view_full_image" to "عرض الصورة الكاملة",
            "success_deleted" to "تم حذف تذكرة العميل %s بنجاح!",
            "empty_search" to "لا توجد تذاكر صيانة مطابقة حالياً",

            // Ticket List
            "ticket_list_title" to "إدارة تذاكر الصيانة والأجهزة",
            "search_placeholder" to "بحث بالاسم أو الهاتف...",
            "ticket_number" to "رقم التذكرة",
            "client" to "العميل:",
            "model" to "الموديل:",
            "fault" to "العطل:",
            "total" to "الإجمالي:",
            "paid" to "المدفوع:",
            "remaining" to "المتبقي:",
            "details_options" to "التفاصيل والخيارات",
            "ticket_details_title" to "تفاصيل تذكرة الصيانة #",
            "edit_ticket" to "تعديل التذكرة",
            "delete" to "حذف",
            "font_size_invoice" to "حجم الخط بالفاتورة",
            "close" to "إغلاق",
            "ticket_status_update" to "حالة التذكرة وتحديث فوري",
            "status_pending_desc" to "الصيانة معلقة - بانتظار فحص",
            "status_inprogress_desc" to "قيد العمل والتصليح",
            "status_parts_desc" to "بانتظار وصول قطع الغيار",
            "status_completed_desc" to "تم الإصلاح بنجاح (جاهز للاستلام)",
            "status_delivered_desc" to "تم تسليم الجهاز للعميل بالكامل",
            "update_status_btn" to "تحديث الحالة",
            "print_share_invoice" to "طباعة ومشاركة الفاتورة",
            "device_photos" to "الصور المرفقة للجهاز",
            "photo_front" to "الأصلية / الأمامية",
            "photo_back" to "الخلفية",
            "no_photos" to "لا توجد صور مرفقة للتذكرة.",
            "tech_notes" to "ملاحظات فنية خاصة بالتذكرة",
            "registration_date" to "تاريخ التسجيل:",
            "since" to "منذ",
            "days" to "أيام",
            "status_pending" to "قيد الانتظار",
            "status_inprogress" to "قيد الصيانة",
            "status_parts" to "قطعة",
            "status_completed" to "مكتمل",
            "status_delivered" to "تم التسليم",

            // Ticket Form (Creation)
            "new_ticket_title" to "إنشاء تذكرة صيانة جديدة",
            "client_device_info" to "بيانات العميل والجهاز",
            "client_name" to "اسم العميل بالكامل",
            "client_name_placeholder" to "اسم العميل الوقع",
            "client_phone" to "رقم هاتف العميل",
            "client_phone_placeholder" to "رقم هاتف العميل للتواصل",
            "device_model" to "نوع وموديل الجهاز",
            "device_model_placeholder" to "موديل الهاتف ومواصفاته",
            "fault_description" to "وصف العطل بدقة",
            "fault_description_placeholder" to "تفاصيل العطل الفني والقطع المطلوبة",
            "fees_cost" to "الحساب المالي والمقدم",
            "total_estimated_cost" to "سعر الصيانة الإجمالي",
            "advance_payment" to "الدفعة المقدمة",
            "remaining_payment" to "المبلغ المتبقي المعلق للدفع:",
            "additional_notes" to "ملاحظات وشروط إضافية",
            "write_tech_notes" to "ملاحظات وشروط استثنائية",
            "device_photo_documentation" to "توثيق صور الهاتف (حماية وضغط تلقائي)",
            "photo_front_side" to "* يضغط النظام الصور تلقائياً لتوفير مساحة التخزين الخاصة بالهاتف.",
            "photo_back_side" to "صورة خلفية الجهاز",
            "take_photo" to "التقاط صورة",
            "change_photo" to "تغيير الصورة",
            "missing_basic_info" to "بيانات أساسية مفقودة",
            "fill_required_fields" to "الرجاء تعبئة الحقول الأساسية لإنشاء التذكرة.",
            "price_positive_error" to "سعر الصيانة يجب أن يكون أكبر من صفر.",
            "save_success_with_id" to "تم حفظ التذكرة بنجاح برقم #",
            "save_ticket" to "حفظ التذكرة",
            "cancel" to "إلغاء",
            "photo_front_captured_success" to "تم التقاط وضغط الصورة الأمامية بنجاح!",
            "photo_back_captured_success" to "تم التقاط وضغط الصورة الخلفية بنجاح!",
            "photo_compression_failed" to "فشل ضغط الصورة الملتقطة",
            "camera_error" to "خطأ في تشغيل الكاميرا: %s",
            "front_side_label" to "الجهة الأمامية",
            "back_side_label" to "الجهة الخلفية",

            // Notifications
            "notifications_title" to "أجهزة تنتظر قطع غيار",
            "notifications_subtitle" to "تنبيهات قطع الغيار",
            "notifications_desc" to "الأجهزة التي يتم تحويل حالتها إلى (قطعة) وتنتظر قطع غيار ستظهر هنا لتتبع فترة الانتظار.",
            "no_notifications" to "لا توجد أجهزة تنتظر قطع حالياً",
            "stopped_since" to "متوقف منذ ",
            "delayed_parts_needed_count" to "الأجهزة المتأخرة بانتظار القطع (%d)",
            "view_details" to "عرض التفاصيل",
            "waiting_duration" to "انتظار الغيار: %d يوم",

            // Settings
            "settings_title" to "الإعدادات",
            "store_info_section" to "بيانات المتجر والشركة",
            "store_name_label" to "اسم المتجر / الشركة",
            "store_phone_label" to "رقم الهاتف للتواصل",
            "store_currency_label" to "العملة النقدية في الفواتير (مثال: د.إ, $, د.ج)",
            "telegram_link_section" to "إعدادات الربط بقناة التليجرام",
            "telegram_token_label" to "رمز توكن البوت لتيليجرام",
            "telegram_chat_id_label" to "معرّف القناة أو الدردشة",
            "telegram_info_note" to "* سيقوم التطبيق بإرسال أي تذكرة صيانة جديدة تسجلها تلقائياً بالمعلومات والصور إلى هذه القناة بمجرد ضغط حفظ التذكرة.",
            "settings_save_success" to "تم حفظ الإعدادات بنجاح!",
            "save_changes" to "حفظ التعديلات",
            "app_language_section" to "لغة التطبيق",
            "choose_language_label" to "اختر اللغة",
            "lang_ar" to "العربية",
            "lang_fr" to "الفرنسية",
            "back_btn" to "رجوع",
            "edit_ticket_dialog_title" to "تعديل بيانات التذكرة #",
            "edit_success" to "تم تعديل التذكرة بنجاح",

            // Share/WhatsApp template
            "share_header" to "*تذكرة صيانة هاتف رقم (#%d)*",
            "share_welcome" to "مرحباً بك في %s! تفاصيل خدمة صيانة هاتفك أدناه:",
            "share_client" to "• اسم العميل: %s",
            "share_phone" to "• رقم العميل: %s",
            "share_date" to "• تاريخ تسجيل الطلبية: %s",
            "share_device" to "• الجهاز: %s",
            "share_fault" to "• العطل المحدد: %s",
            "share_status" to "• حالة الجهاز: %s",
            "share_total" to "• السعر الكلي: %s %s",
            "share_advance" to "• الدفعة المقدمة: %s %s",
            "share_remaining" to "• المتبقي لسداده: %s %s",
            "share_store_phone" to "• هاتف المتجر: %s",
            "share_notes" to "• ملاحظات إضافية: %s",
            "share_footer" to "شكرًا لثقتك بنا!",
            "share_dialog_title" to "إرسال ومشاركة تفاصيل الصيانة",
            "unpaid_label" to "(متبقي %s %s)",
            "paid_label" to "(مدفوع)",
            "invoice_pdf_chooser" to "مشاركة فاتورة صيانة الهاتف",
            "pdf_error" to "فشل إنشاء فاتورة PDF الموحدة",
            "status_parts_full_desc" to "بانتظار قطعة غيار",
            "status_completed_full_desc" to "تم الانتهاء وجاهز للتسليم",
            "status_delivered_full_desc" to "تم التسليم ومكتمل الحساب",
            "close_btn" to "إغلاق",
            "edit_ticket_btn" to "تعديل التذكرة",
            "client_label_col" to "العميل:",
            "phone_label_col" to "الهاتف:",
            "device_label_col" to "نوع وهاتف الجهاز:",
            "fault_label_col" to "عطل الجهاز:",
            "entry_date_col" to "تاريخ الدخول:",
            "total_price_col" to "السعر الإجمالي للخدمة:",
            "advance_payment_col" to "المبلغ المدفوع (مقدماً):",
            "remaining_payment_col" to "المبلغ المتبقي:",
            "additional_notes_col" to "ملاحظات وشروط إضافية:",
            "documented_photos_label" to "الصور الموثقة للجهاز (انقر لعرضها بالكامل):",
            "change_ticket_status_label" to "تغيير حالة الصيانة للتذكرة:",
            "btn_pending" to "معلق",
            "btn_in_progress" to "بالصيانة",
            "btn_part_needed" to "قطعة",
            "btn_completed" to "جاهز",
            "btn_delivered" to "سلمت",
            "share_pdf_chooser_title" to "مشاركة فاتورة صيانة الهاتف",
            "pdf_generation_failed" to "فشل إنشاء فاتورة PDF الموحدة",
            "share_pdf_btn" to "مشاركة PDF",
            "whatsapp_text_btn" to "واتساب / نص",
            "delete_ticket_btn" to "حذف التذكرة المحددة بصفة نهائية",
            "edit_ticket_title_tk" to "تعديل بيانات التذكرة #%d",
            "save_changes_btn" to "حفظ التعديلات",
            "delete_confirm_title" to "تأكيد الحذف الآمن",
            "delete_confirm_msg" to "هل أنت متأكد تماماً من رغبتك في حذف تذكرة صيانة العميل/الزبون (%s) نهائياً من النظام؟ لا يمكن الرجوع عن هذا الخيار بعد تأكيده.",
            "ticket_deleted_success_toast" to "تم حذف تذكرة العميل %s بنجاح!",
            "call_failed_toast" to "فشل بدء المكالمة",
            "call_client_action" to "اتصال بالعميل",
            "share_btn_text" to "إرسال ومشاركة تفاصيل الصيانة",
            "revenue_details_title" to "تفاصيل الأرباح والمداخيل",
            "total_sales_subtitle" to "مجموع المبيعات والمقدمات",
            "whatsapp_share_template" to "*تذكرة صيانة هاتف رقم (#%s)*\nمرحباً بك في %s! تفاصيل خدمة صيانة هاتفك أدناه:\n\n• اسم العميل: %s\n• رقم العميل: %s\n• تاريخ تسجيل الطلبية: %s\n• الجهاز: %s\n• العطل المحدد: %s\n• حالة الجهاز: %s\n\n------------------------------\n• السعر الكلي: %s\n• الدفعة المقدمة: %s\n• المتبقي لسداده: %s\n------------------------------\n• هاتف المتجر: %s\n------------------------------\n\nشكرًا لثقتك بنا!",
            
            // Missing UI Keys
            "this_month" to "هذا الشهر",
            "this_week" to "هذا الأسبوع",
            "completed_tickets_stat" to "أجهزة جاهزة للتسليم",
            "active_tickets_stat" to "أجهزة قيد الصيانة",
            "revenue_stats" to "إحصائيات الأرباح والمداخيل",
            "no_pending_tickets_empty" to "لا توجد تذاكر صيانة معلقة حالياً! 👍",
            "active_maintenance_device" to "الجهاز قيد الصيانة حالياً",
            "no_active_maintenance_empty" to "لا توجد أجهزة قيد الصيانة النشطة حالياً! 👍",
            "remaining_payment_short" to "المتبقي",
            "client_label_simple" to "العميل",
            "phone_label_simple" to "الهاتف",
            "device_label_simple" to "الجهاز",
            "fault_label_simple" to "العطل",
            "forgotten_devices_shop" to "أجهزة جاهزة لم تُسترجع",
            "ticket_number_label" to "تذكرة صيانة رقم #%d",
            "ticket_shifted_to_progress_toast" to "تم نقل التذكرة رقم #%d إلى قيد الصيانة",
            "ticket_shifted_to_unclaimed_toast" to "تم نقل التذكرة رقم #%d إلى جاهز للتسليم",
            "start_maintenance_action" to "بدء الصيانة",
            "skip_to_next_action" to "التالي",
            "reset_to_first_action" to "الأول",
            "ready_for_delivery" to "جاهز للتسليم",
            "no_unclaimed_devices_empty" to "لا توجد أجهزة جاهزة معلقة بانتظار الاستلام 👍",
            "pending_status" to "معلق",
            "in_progress_status" to "قيد الصيانة",
            "part_needed_status" to "بانتظار قطعة",
            "completed_status" to "جاهز للتسليم",
            "delivered_status" to "تم التسليم"
        ),
        "fr" to mapOf(
            // App main
            "app_name" to "Maintenance Pro",
            "premium_version" to "Version Activée (Premium)",
            "nav_metrics" to "Indicateurs",
            "nav_tickets" to "Tickets",
            "nav_settings" to "Paramètres",
            "nav_notifications" to "Notifications",
            "user_profile" to "Profil",

            // Activation
            "activation_title" to "Activation de l'application",
            "activation_welcome" to "Bienvenue dans l'application de Maintenance",
            "activation_desc" to "Cette application est licenciée et nécessite une clé d'activation lors de sa première ouverture.",
            "device_id_label" to "Identifiant unique de votre appareil (DeviceID):",
            "device_id_copied" to "ID de l'appareil copié!",
            "activation_key_label" to "Saisir la clé d'activation",
            "activation_key_placeholder" to "Clé Base64",
            "activation_key_required" to "Veuillez d'abord saisir la clé d'activation.",
            "activation_key_invalid" to "Clé d'activation invalide ou non attribuée à cet appareil/cette année.",
            "activation_success" to "Application activée avec succès!",
            "activate_now" to "Activer maintenant",

            // Dashboard
            "dashboard_title" to "Tableau de Bord & Statistiques",
            "total_tickets" to "Total des tickets enregistrés",
            "pending_tickets" to "Tickets attente",
            "inprogress_tickets" to "Tickets cours de réparation",
            "parts_needed_tickets" to "Tickets attente de pièces",
            "completed_tickets" to "Appareils réparés attente de collecte",
            "delivered_tickets" to "Appareils livrés et réglés",
            "financial_analysis" to "Statistiques des Gains",
            "expected_revenue" to "Total des revenus prévus",
            "collected_revenue" to "Total des acomptes perçus",
            "remaining_revenue" to "Total restant à percevoir",
            "parts_needed_report" to "Rapport des pièces de rechange requises",
            "status_statistics" to "Statistiques par statut",
            "percentage" to "Pourcentage",
            "ticket" to "ticket(s)",
            "next_ticket_queue" to "Prochain ticket attente",
            "start_maintenance" to "Démarrer la réparation",
            "skip_next" to "Ticket suivant",
            "go_to_first" to "Premier ticket",
            "phone_label" to "Tél :",
            "device_label" to "Appareil :",
            "no_pending_queue" to "Aucun ticket attente actuellement 👍",
            "current_maintenance_device" to "Appareil cours de réparation",
            "ready_delivery" to "Prêt pour livraison",
            "no_active_repairs" to "Aucun appareil cours de réparation 👍",
            "forgotten_devices" to "Appareils prêts non récupérés",
            "today" to "Aujourd'hui",
            "since_1_day" to "Depuis 1 jour",
            "since_2_days" to "Depuis 2 jours",
            "since_x_days" to "Depuis %d jours",
            "since_many_days" to "Depuis %d jours",
            "no_forgotten_devices" to "Aucun appareil oublié ou prêt attente 👍",
            "call_client" to "Appeler le client",
            "device_type_phone" to "Appareil / Modèle :",
            "device_fault" to "Détails de la panne :",
            "entry_date" to "Date d'entrée :",
            "total_service_price" to "Prix total du service :",
            "advance_payment_label" to "Acompte payé :",
            "remaining_payment_label" to "Montant restant :",
            "additional_notes_comments" to "Notes & Conditions :",
            "device_photos_title" to "Photos de l'appareil (Sélect. pour zoomer) :",
            "change_maintenance_status" to "Mettre à jour l'état du ticket :",
            "share_pdf" to "Partager PDF",
            "share_text" to "WhatsApp / SMS",
            "delete_selected_permanently" to "Supprimer définitivement ce ticket",
            "edit_ticket_dialog_title" to "Modifier le ticket N° #",
            "save_edits" to "Enregistrer les modifications",
            "cancel_btn" to "Annuler",
            "confirm_delete_title" to "Confirmer la suppression",
            "confirm_delete_msg" to "Êtes-vous sûr de vouloir supprimer définitivement le ticket de (%s) ? Cette action est irréversible.",
            "yes_confirm_delete" to "Oui, Supprimer",
            "view_full_image" to "Image complète",
            "success_deleted" to "Ticket de %s supprimé avec succès !",
            "empty_search" to "Aucun ticket correspondant trouvé",

            // Ticket List
            "ticket_list_title" to "Gestion des tickets de maintenance",
            "search_placeholder" to "Rechercher par nom ou tél...",
            "ticket_number" to "N° Ticket",
            "client" to "Client :",
            "model" to "Modèle :",
            "fault" to "Panne :",
            "total" to "Total :",
            "paid" to "Payé :",
            "remaining" to "Reste :",
            "details_options" to "Détails & Options",
            "ticket_details_title" to "Détails du ticket #",
            "edit_ticket" to "Modifier le ticket",
            "delete" to "Supprimer",
            "font_size_invoice" to "Taille police du reçu",
            "close" to "Fermer",
            "ticket_status_update" to "État du ticket et mise à jour",
            "status_pending_desc" to "Attente d'évaluation",
            "status_inprogress_desc" to "Cours de réparation",
            "status_parts_desc" to "Attente de pièces de rechange",
            "status_completed_desc" to "Réparation terminée (Prêt)",
            "status_delivered_desc" to "Appareil livré au client",
            "update_status_btn" to "Mettre à jour l'état",
            "print_share_invoice" to "Imprimer / Partager le reçu",
            "device_photos" to "Photos de l'appareil",
            "photo_front" to "Face avant",
            "photo_back" to "Face arrière",
            "no_photos" to "Aucune photo jointe.",
            "tech_notes" to "Notes techniques du ticket",
            "registration_date" to "Date d'enregistrement :",
            "since" to "Depuis",
            "days" to "jour(s)",
            "status_pending" to "Attente",
            "status_inprogress" to "Cours",
            "status_parts" to "Pièces",
            "status_completed" to "fini",
            "status_delivered" to "Livré",

            // Ticket Form (Creation)
            "new_ticket_title" to "Créer un nouveau ticket",
            "client_device_info" to "Informations client & appareil",
            "client_name" to "Nom complet du client",
            "client_name_placeholder" to "Nom du client",
            "client_phone" to "Numéro de téléphone",
            "client_phone_placeholder" to "Numéro de téléphone",
            "device_model" to "Marque et modèle",
            "device_model_placeholder" to "Modèle de l'appareil",
            "fault_description" to "Description de la panne",
            "fault_description_placeholder" to "Description détaillée de la panne",
            "fees_cost" to "Aspects financiers",
            "total_estimated_cost" to "Coût total de réparation",
            "advance_payment" to "Acompte payé (avance)",
            "remaining_payment" to "Montant restant à payer :",
            "additional_notes" to "Notes et conditions",
            "write_tech_notes" to "Conditions ou remarques exceptionnelles",
            "device_photo_documentation" to "Documentation photos (Compression intégrée)",
            "photo_front_side" to "* Le système réduit la taille des photos pour économiser l'espace de stockage d'appareil.",
            "photo_back_side" to "Photo arrière de l'appareil",
            "take_photo" to "Prendre photo",
            "change_photo" to "Modifier photo",
            "missing_basic_info" to "Champs obligatoires manquants",
            "fill_required_fields" to "Veuillez remplir les informations de base pour le ticket.",
            "price_positive_error" to "Le prix de réparation doit être supérieur à zéro.",
            "save_success_with_id" to "Ticket enregistré avec succès sous le N° #",
            "save_ticket" to "Enregistrer le ticket",
            "cancel" to "Annuler",
            "photo_front_captured_success" to "Image avant capturée et compressée avec succès !",
            "photo_back_captured_success" to "Image arrière capturée et compressée avec succès !",
            "photo_compression_failed" to "Échec de compression d'image",
            "camera_error" to "Erreur d'initialisation caméra : %s",
            "front_side_label" to "Face avant",
            "back_side_label" to "Face arrière",

            // Notifications
            "notifications_title" to "Appareils attente de pièces",
            "notifications_subtitle" to "Alertes pièces de rechange",
            "notifications_desc" to "Les appareils marqués (Pièces) s'afficheront ici pour suivre l'attente des pièces.",
            "no_notifications" to "Aucun appareil attente de pièces de rechange 👍",
            "stopped_since" to "Suspendu depuis ",
            "delayed_parts_needed_count" to "Appareils attente de pièces (%d)",
            "view_details" to "Voir détails",
            "waiting_duration" to "Attente de pièce : %d j",

            // Settings
            "settings_title" to "Paramètres",
            "store_info_section" to "Données de la boutique",
            "store_name_label" to "Nom de la boutique / société",
            "store_phone_label" to "Numéro de téléphone de contact",
            "store_currency_label" to "Devise par défaut (ex: €, $, د.إ)",
            "telegram_link_section" to "Paramètres d'intégration Telegram",
            "telegram_token_label" to "Token du bot Telegram",
            "telegram_chat_id_label" to "ID canal / chat Telegram",
            "telegram_info_note" to "* L'application enverra automatiquement chaque nouveau ticket enregistré avec ses données et photos sur ce canal d'information.",
            "settings_save_success" to "Paramètres enregistrés avec succès !",
            "save_changes" to "Enregistrer",
            "app_language_section" to "Langue de l'application",
            "choose_language_label" to "Sélectionner la langue",
            "lang_ar" to "Arabe",
            "lang_fr" to "Français",
            "back_btn" to "Retour",
            "edit_ticket_dialog_title" to "Modifier données du ticket #",
            "edit_success" to "Ticket modifié avec succès !",

            // Share/WhatsApp template
            "share_header" to "*Ticket de maintenance N° (#%d)*",
            "share_welcome" to "Bienvenue chez %s ! Voici les détails de votre appareil :",
            "share_client" to "• Nom du client : %s",
            "share_phone" to "• Téléphone : %s",
            "share_date" to "• Date d'enregistrement : %s",
            "share_device" to "• Appareil : %s",
            "share_fault" to "• Panne signalée : %s",
            "share_status" to "• État de réparation : %s",
            "share_total" to "• Coût total : %s %s",
            "share_advance" to "• Acompte payé : %s %s",
            "share_remaining" to "• Reste à payer : %s %s",
            "share_store_phone" to "• Tél. boutique : %s",
            "share_notes" to "• Notes : %s",
            "share_footer" to "Merci d'avoir choisi nos services !",
            "share_dialog_title" to "Partager détails de maintenance",
            "unpaid_label" to "(reste %s %s)",
            "paid_label" to "(payé)",
            "invoice_pdf_chooser" to "Partager le ticket PDF",
            "pdf_error" to "Échec de génération du PDF officiel",
            "status_parts_full_desc" to "Attente de pièces",
            "status_completed_full_desc" to "Réparation terminée, prêt pour retrait",
            "status_delivered_full_desc" to "Livré et totalement payé",
            "close_btn" to "Fermer",
            "edit_ticket_btn" to "Modifier le ticket",
            "client_label_col" to "Client :",
            "phone_label_col" to "Téléphone :",
            "device_label_col" to "Appareil :",
            "fault_label_col" to "Panne :",
            "entry_date_col" to "Date d'entrée :",
            "total_price_col" to "Coût total :",
            "advance_payment_col" to "Acompte payé :",
            "remaining_payment_col" to "Montant restant :",
            "additional_notes_col" to "Notes & Conditions :",
            "documented_photos_label" to "Photos de l'appareil (Sélect. pour zoomer) :",
            "change_ticket_status_label" to "Mettre à jour l'état du ticket :",
            "btn_pending" to "Attente",
            "btn_in_progress" to "Cours",
            "btn_part_needed" to "Pièces",
            "btn_completed" to "fini",
            "btn_delivered" to "Livré",
            "share_pdf_chooser_title" to "Partager le ticket PDF",
            "pdf_generation_failed" to "Échec de génération du PDF officiel",
            "share_pdf_btn" to "Partager PDF",
            "whatsapp_text_btn" to "WhatsApp / SMS",
            "delete_ticket_btn" to "Supprimer",
            "edit_ticket_title_tk" to "Modifier données du ticket #%d",
            "save_changes_btn" to "Enregistrer",
            "delete_confirm_title" to "Confirmer la suppression",
            "delete_confirm_msg" to "Êtes-vous sûr de vouloir supprimer définitivement le ticket de (%s) ? Cette action est irréversible.",
            "ticket_deleted_success_toast" to "Ticket de %s supprimé avec succès !",
            "call_failed_toast" to "Échec du démarrage de l'appel",
            "call_client_action" to "Appeler le client",
            "share_btn_text" to "Partager détails de maintenance",
            "revenue_details_title" to "Détails des gains",
            "total_sales_subtitle" to "Total des ventes et acomptes",
            "whatsapp_share_template" to "*Ticket de maintenance N° (#%s)*\nBienvenue chez %s ! Voici les détails de votre appareil :\n\n• Nom du client : %s\n• Téléphone : %s\n• Date d'enregistrement : %s\n• Appareil : %s\n• Panne signalée : %s\n• État de réparation : %s\n\n------------------------------\n• Coût total : %s\n• Acompte payé : %s\n• Reste à payer : %s\n------------------------------\n• Tél. boutique : %s\n------------------------------\n\nMerci d'avoir choisi nos services !",
            
            // Missing UI Keys
            "this_month" to "Ce mois-ci",
            "this_week" to "Cette semaine",
            "completed_tickets_stat" to "Appareils réparés",
            "active_tickets_stat" to "Appareils en cours",
            "revenue_stats" to "Statistiques des Gains",
            "no_pending_tickets_empty" to "Aucun ticket en attente actuellement ! 👍",
            "active_maintenance_device" to "Appareil en cours de réparation",
            "no_active_maintenance_empty" to "Aucun appareil en cours de réparation ! 👍",
            "remaining_payment_short" to "Reste",
            "client_label_simple" to "Client",
            "phone_label_simple" to "Tél",
            "device_label_simple" to "Appareil",
            "fault_label_simple" to "Panne",
            "forgotten_devices_shop" to "Appareils prêts non récupérés",
            "ticket_number_label" to "Ticket N° #%d",
            "ticket_shifted_to_progress_toast" to "Ticket N° #%d mis en cours de réparation",
            "ticket_shifted_to_unclaimed_toast" to "Ticket N° #%d mis en prêt pour livraison",
            "start_maintenance_action" to "Démarrer la réparation",
            "skip_to_next_action" to "Suivant",
            "reset_to_first_action" to "Premier",
            "ready_for_delivery" to "Prêt pour livraison",
            "no_unclaimed_devices_empty" to "Aucun appareil prêt non récupéré 👍",
            "pending_status" to "Attente",
            "in_progress_status" to "Cours",
            "part_needed_status" to "Pièces",
            "completed_status" to "fini",
            "delivered_status" to "Livré"
        )
    )

    fun get(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["ar"]!!
        return dict[key] ?: translations["ar"]!![key] ?: key
    }
}
